-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrUQxN6DssgYihtpp
XZ+nq/Ow6tyjyQmy1EqlEZGZsTWgCgYIKoZIzj0DAQehRANCAAT5ky6GsddXj88P
yhj+VIwGsmPty8W7Kb9DOsEdeUhSQrht2pgbyAXxfhxTKadL4Hp8wrGSJuF0jwzd
FJsuhvDJ
-----END PRIVATE KEY-----