-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbasAQykFudcj9O2n
rRbdjAszBtI10QrMhiiZ5hZ/5zWgCgYIKoZIzj0DAQehRANCAASyaiiDf4eySkQu
7ANsS3R8lAAmq/VLbZAWqZGdecLWVKv/7tPf3w6EpKvJKK5cInGkaYNfskTCasi2
WtjkADHD
-----END PRIVATE KEY-----